---
title: "Kaggle"
author: "Scott Brenstuhl"
date: "May 29, 2016"
output: html_document
---


```{r, echo = FALSE}
# setwd("/Users/scottbrenstuhl/Projects/AnalyticsEdge/Analytics_Edge_Kaggle/")

library(caret)
library(dplyr)
library(ggplot2)
library(mice)
library(readr)

training <- read.csv("data/train2016.csv", na.strings = c("NA",""))
testing <- read.csv("data/test2016.csv", na.strings = c("NA",""))
```


# Exploration
```{r, echo=FALSE}
str(training)

# Commented out to avoid Rmd error
#View(head(training,10))

prop.table(table(complete.cases(training)))

# No overlap in user_ids to exploit 
table(testing$USER_ID %in% training$USER_ID)
```

Very low percent of respondednts answered all questions so I will need to figure out some good impution strategies.


```{r, echo=FALSE}

CART <- rpart(Party ~., data = training)

prp(CART)


```


```{r, echo=FALSE}
# Make data sets considering NA a choice of no response

removeNA <- function(x){
    if(is.factor(x) & sum(is.na(x)) > 0){
        factor(as.character(x), levels = c(levels(x), "noResponse"))
    }else{
            x
        }
    }

trainNoAns <- as.data.frame(lapply(training, removeNA))
testNoAns <- as.data.frame(lapply(testing, removeNA))


trainNoAns[,-2][is.na(trainNoAns[,-2])] <- "noResponse"
testNoAns[,-2][is.na(testNoAns[,-2])] <- "noResponse"
head(trainNoAns[,-1:-2])
head(trainNoAns[,1:5])
```

```{r, echo = FALSE}

percent_missing <- function(column){
        col_table <- prop.table(table(column, useNA = "always"))
        as.numeric(col_table[is.na(names(col_table))])
    }

ans_missing <- lapply(training, percent_missing) 
ans_missing <- data_frame(qustion = names(ans_missing),
                          perc_missing = as.numeric(ans_missing))


qplot(qustion, y=perc_missing, data = subset(ans_missing, perc_missing >.45 ))
qplot(qustion, y=perc_missing, data = subset(ans_missing, perc_missing <.30 ))
qplot(qustion, y=perc_missing, data = subset(ans_missing, perc_missing >.30 &
                                                 perc_missing <.45 ))
```

Q124742 is missing a lot more responses than the rest so it will probably be
best to remove it.

Only the non-question (demagraphics) have less than 30% missing which isn't too
surprising.

```{r, echo = FALSE}
# Not so helpful but want to remember it for now
#md.pattern(training)
methods(mice)

# This might be better to do after deciding which columns to use?
missing_perc <- apply(is.na(training),1,function(x) sum(x)/108)
table(round(missing_perc, digits = 1))
prop.table(table(missing_perc >.5))

dim(training)

```



```{r, echo = FALSE}

baseGLM <- glm(Party~.-USER_ID, training, family = binomial)
summary(baseGLM)

noAnsGLM <- glm(Party~.-USER_ID, trainNoAns, family = binomial)
summary(noAnsGLM)

class(training$YOB)
class(trainNoAns$YOB)
```


```{r, echo=FALSE, cache= TRUE}

noAnsRF <- rf(Party~.-USER_ID , data = trainNoAns)

```
